version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/hsrp
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - hsrp-network

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - hsrp-network
    environment:
      - MONGO_INITDB_DATABASE=hsrp

volumes:
  mongo-data:

networks:
  hsrp-network:
    driver: bridge
